export const setTodoAction ='setJob'
export const addTodoAction ='add'
export const removeTodoAction ='remove'
export const updateTodoAction ='update'
export const updateTodoListAction ='updateTodoList'